name: Notify Discord on CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '✅ GitHub Actions 성공: ${{ github.repository }} #${{ github.run_number }}'